#!/bin/bash

#set -x

HOME=/home/nexedi
FOLDER_PATH="/home/nexedi/videogranulate_buildout"
OPTS=""

videogranulatectl_path="$FOLDER_PATH/bin"
pid_path="$FOLDER_PATH/run"

. /lib/lsb/init-functions

case "$1" in
  start)
     log_daemon_msg "Starting a VideoGranulate server..." "videogranulate"
     if start-stop-daemon -c nexedi --start --quiet --oknodo --pidfile $pid_path/videogranulate.pid --exec \
        $videogranulatectl_path/videogranulate_ctl start $OPTS; then
        log_end_msg 0
     else
        log_end_msg 1
     fi
     ;;

  stop)
     log_daemon_msg "Stoping VideoGranulate server..." "videogranulate"
     if start-stop-daemon -c nexedi --stop --quiet --oknodo --pidfile $pid_path/videogranulate.pid; then
        log_end_msg 0
     else
        log_end_msg 1
     fi
     ;;

  status)
     status_of_proc -p $pid_path/videogranulate.pid $videogranulatectl_path/videogranulate_ctl videogranulate && exit 0 || exit $?
     ;;

  *)
    log_action_msg "Usage: /etc/init.d/videogranulate {start|stop|status}"
    exit 1
esac

exit 0
